### ISSUE TITLE
Issue while running python code to get the claims data 

### ISSUE THREAD

**Issue by Ratanr** [OHDSI/ETL-CMS#50]
Hi All,

I am trying to run the Python code to get the claims data directly from the website that is available on the site i.e **get_synpuf_files.py**. but I am getting the syntax error. could you please let me know the correct steps to run this successfully?

![image](https://user-images.githubusercontent.com/21287124/37356556-a8a075d8-26bc-11e8-8cec-4d7d7e29d93c.png)

Thanks,
Ratan

**Comment by ericaVoss** [comment]
Are you just looking to get a copy of the data?  You don't need to generate it yourself.  In fact we just updated to V5.2.

This doesn't solve the Python issue, but you don't need to solve it if you just want the data.  

Let me know and then we can work on getting it to you.  Since we just finished generating it we don't have it formally released somewhere yet.

**Comment by Ratanr** [comment]
Hi Erica,

I only need a copy of CMS synthetic claims data. I was able to manually download the claims data DE_1 to DE_20 from CMS site.  

Since we have to convert one of the datasets to CDM and I am new to ODHSI so wanted to understand the full workflow of it by executing all the steps of the different dataset.  I will be able to use the data which I downloaded manually but still wanted to understand why that particular code did not work?.
I am also having problems with other steps which I will be posting after trying all alternatives from my side.

Thank you for the updates on V5.2. Any particular date on which the V5.2 is getting released?

Thanks,
Ratan

**Comment by ChristopheLambert** [comment]
Hi Ratan,

You did not type the python command at the beginning of your command line. Plus you did not specify a valid output directory. You should replace "path/to/output/directory" with a pathname of where to store the data. It is also strange  you are currently working from the Python27 directory -- presumably your installation directory for python, instead of a folder where all of the ETL-CMS files are stored.

Sincerely,
Christophe

**Comment by Ratanr** [comment]
Hi Chris,

sorry for the confusion, I just used the path as an example however I missed the python command at the beginning of command line.

I have used the below path to generate output files but still getting the same issue. please suggest a way forward.

![image](https://user-images.githubusercontent.com/21287124/37372234-69adf39c-26e8-11e8-9a46-b568c4d577d6.png)

Thanks,
Ratan

**Comment by ChristopheLambert** [comment]
Look inside the python file and see if it looks like html. If so, you did not properly retrieve it from github -- make sure to get the raw version of the file.

Christophe

**Comment by Ratanr** [comment]
Hi Christophe,

done. I was able to execute and download the data from my side now. Thank you.

I was having some problem because of JDK version.

Thanks,
Ratan
